default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: google_scraper_development
  host: localhost
  port: 5432
  username: <%= Settings.database.username %>
  password: <%= Settings.database.password %>

test:
  <<: *default
  database: google_scraper_test

production:
  <<: *default
  database: google_scraper_production
  username: google_scraper
  password: <%= ENV["GOOGLE_SCRAPER_DATABASE_PASSWORD"] %>
